### ISSUE TITLE
Queue stops processing

### ISSUE THREAD

**Issue by jasoncox** [brainopia/sidekiq-limit_fetch#50]
sidekiq (3.3.1) & sidekiq-limit_fetch (2.3.0)

I have the following queues:
```YAML
:queues:
  - [default]
  - [recurring]
  - [carrierwave]
  - [accounting]
  - [itunes]
:limits:
    accounting: 1
    itunes: 1
```

The itunes queue runs every 24hrs and processes around 200 individual jobs.

Accounting is constantly processing jobs, but stops processing jobs after the itunes queue is run... then the jobs in accounting are enqueued but never processed. Restart sidekiq gets everything going again.

Have you seen this behaviour before? Have I configured something wrong?
