### ISSUE TITLE
Configuration not working via sidekiq options just after redis db was flushed

### ISSUE THREAD

**Issue by rubyconvict** [brainopia/sidekiq-limit_fetch#57]
my config:
```
    workers:
      verbose: true
      concurrency: 40
      :queues:
        - heartbeat
        - default
        - seldom
      :process_limits:
        heartbeat: 1
        default: 38
        seldom: 1
```
how to reproduce (assuming sidekiq is using db nr 10):
```
redis-cli
select 10
flushdb
```
put somewhere in the initializer (after sidekiq setup)
```
  Sidekiq.options[:process_limits] = Settings.workers.try(:[], :":process_limits") if Settings.workers.include?(:":process_limits")
  puts Sidekiq.options
  puts "limit fetch: default -> #{Sidekiq::Queue['default'].process_limit}"
```
or omit Settings setup and just put
```
  Sidekiq.options[:process_limits] = {:heartbeat=>1, :default=>38, :seldom=>1}
  puts Sidekiq.options
  puts "limit fetch: default -> #{Sidekiq::Queue['default'].process_limit}"
```
outcome
```
{:queues=>["heartbeat", "default", "seldom"], :labels=>[], :concurrency=>40, 
[OMITTED] :fetch=>Sidekiq::LimitFetch, :verbose=>true, :process_limits=>{:heartbeat=>1, :default=>38, :seldom=>1}}
limit fetch: default ->
```
Setting it dynamically is fine, or restarting the process, so maybe there should be some warning (at least in README.md) or can I get info how to do it properly it this case?
