### ISSUE TITLE
Sidekiq not processing queues with limits on Redis reconnect

### ISSUE THREAD

**Issue by bardhi** [brainopia/sidekiq-limit_fetch#72]
When Redis dies and comes back up, or if there is a temporary connectivity issue, Sidekiq is able to reconnect and process new jobs. However, when using limit_fetch to set a limit on a queue, processing jobs on that limited queue no longer works properly. Specifically, I have a queue with a limit of 1. This is what my config looks like:

```
defaults: &defaults
  concurrency: 25
  namespace: 'sidekiq'
  sentinels:
    - {host: '127.0.0.1', port: '26379'}
  url: 'redis://mymaster'
  :queues:
    - sequential
    - default
  :limits:
    sequential: 1
```

Upon reconnect, jobs sent to the `default` queue get processed just fine, but not jobs sent to `sequential`. 

I believe this is happening because the way that sidekiq-limit_fetch ensures the limit is by adding an entry for each Sidekiq process to the sidekiq:limit_fetch:probed:<queue_name> list in Redis. I suspect that whatever thread needs to clean up the lock fails when connectivity to Redis is lost, and the process does not remember to clean it up upon reconnecting. It looks like a call to `selector.release(queues, namespace)` with the name of the limited queue never happens, so the thread does not get cleaned up.

Is this a known issue, and if so are there any plans to make sidekiq-limit_fetch able to handle reconnects? In the meantime, is the best option to restart sidekiq when connectivity is lost?

I am using sidekiq-limit_fetch 3.1.0 and sidekiq 4.0.2.

Thanks!
